### ISSUE TITLE
ActionView::Template::Error (execution expired)

### ISSUE THREAD

**Issue by nguyenngoc2505** [mileszs/wicked_pdf#1021]
I've problem when using wicked_pdf_stylesheet_link_tag, it happens 3 times at 1 point (then automatically resolved)

```
F, [2022-04-12T22:37:29.824976 #29312] FATAL -- : [918aef5a-4a88-4002-977c-bd64d276c577] ActionView::Template::Error (execution expired):
F, [2022-04-12T22:37:29.825076 #29312] FATAL -- : [918aef5a-4a88-4002-977c-bd64d276c577]      5:     <meta charset="utf-8" />
[918aef5a-4a88-4002-977c-bd64d276c577]      6:     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />
[918aef5a-4a88-4002-977c-bd64d276c577]      7:     <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Barlow:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" />
[918aef5a-4a88-4002-977c-bd64d276c577]      8:     <%= wicked_pdf_stylesheet_link_tag :wicked_pdf %>

# backtrace

execution expired
/home/user/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/resolv-replace.rb:25:in initialize'
/home/user/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/resolv-replace.rb:25:ininitialize’
/home/user/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:937:in `open’
```

I think it's a network error, unrelated to wicked_pdf. Does anyone have any ideals for this error?

**Comment by unixmonkey** [comment]
> ActionView::Template::Error (execution expired)

Sounds like this is a timeout happening trying to live-compile the `:wicked_pdf` stylesheet, which should be precompiled in production, so I'm guessing you are getting this in development mode.

A reason I could think this timeout might happen is if inside the stylesheet you are including an asset that makes a request that lives at another endpoint in the app, which is either unreachable, or causing a deadlock.

> executation expired
> resolv-replace.rb: in initialize

This seems to make sense that it's trying to get an external asset. Something about HTTP resolving an asset taking too long.

It might be in a deadlock because it is easy to have a local Rails development server that can only handle one or two requests at the same time, so if it needs to make a request in the process of making a request, the second request is queued, and the first request never finishes.

**Comment by nguyenngoc2505** [comment]
@unixmonkey Thankyou, btw it happened on production mode not development mode.
