### ISSUE TITLE
ERROR:  Failed to load PDF document.

### ISSUE THREAD

**Issue by Shivyoddha** [mileszs/wicked_pdf#1050]
## Issue description
I am getting this error for a long time, i am using wicked pdf for first  time can anyone please guide me out.
![image](https://user-images.githubusercontent.com/97729353/219472538-118aede4-76cf-4af2-8049-9f06cc2b8b30.png)
![image](https://user-images.githubusercontent.com/97729353/219472676-0414e228-b188-4963-8c76-c78da9e10cef.png)
![image](https://user-images.githubusercontent.com/97729353/219472751-7770e1e0-c694-4832-a3fa-20650aed908a.png)

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):

wkhtmltopdf version (output of `wkhtmltopdf --version`):

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar):

**Comment by unixmonkey** [comment]
There is not enough information in this post to determine what's going on, but I suspect the templates are being loaded just fine, but that `wkhtmltopdf` is either not installed, or possibly unable to run due to it's installation missing libraries, no access to tempfiles, or something like that.

Closing this issue since it's so old, but if you are still having issues please let me know and I'll reopen and try to help you out.
If you could add the "System specifications" info, that would also be helpful.

Thanks!
