### ISSUE TITLE
Can we get a new Release 

### ISSUE THREAD

**Issue by wizardofelves** [mileszs/wicked_pdf#1069]
The last version of Wicked PDF was released in May last year, and since then there have been some great changes - would it be possible to get a new release / version bump so that we can reference these new changes in our Gemfile w/ a version number? Thank you

**Comment by unixmonkey** [comment]
I'm planning on releasing very soon, but the one thing that really hangs me up is updating the CHANGELOG (and often backwards-compatibility testing).

If you could help by adding entries for the new stuff and changing the version (following SEMVER), I could probably cut a release today. Otherwise I'll try to get to it in the next few days.

**Comment by wizardofelves** [comment]
@unixmonkey  I created a PR that should get you mostly there. Thank you for your work on this project.

**Comment by unixmonkey** [comment]
We've now released version 2.7.0 of wicked_pdf. Thank you for your help!
