### ISSUE TITLE
wicked_pdf and remotipart gems can't coexist

### ISSUE THREAD

**Issue by woodwardjd** [mileszs/wicked_pdf#111]
I don't have the depth of expertise to identify if one or both projects are doing something inadvisable, so I'm posting this on both projects in the hope that someone more knowledgeable will be able to point out a fix to one or both parties.  At the very least, these gems don't seem to play well together.  

Both gems mess with the render method in ActionController::Base.  wicked_pdf does method chaining and remotipart does it by calling super.

When wicked_pdf and remotipart are both loaded in the Gemfile part of remotipart ceases to function.

See https://github.com/JangoSteve/remotipart/issues/27 for more details.

**Comment by ilucin** [comment]
I have the same issue with Turbolinks. Turbolinks is also overriding render and when I add wicked_pdf gem that override stops working. Commenting out self.included (as mentioned above) works but I would like to avoid using forked library just because of this issue.

Since Turbolinks is kinda official rails lib (they are really pushing it) I would try to come up with a solution for this. I'm not a ruby developer so I can't really help much :/

**Comment by Grammarella** [comment]
+1

We use the forked branch and have to avoid updating the gem due to this issue.

**Comment by unixmonkey** [comment]
This should be solved with the merge of #574 

Please reopen if there are any further issues after upgrading.

**Comment by pierre-alain-b** [comment]
Hi there,

I see this problem popping up again with wicked_pdf 2.0.1 and remotipart 1.4.x. If I downgrade to wicked_pdf 1.4.0, the problem disappears.

Best
Pierre

**Comment by unixmonkey** [comment]
The only thing that I can see that could be causing this for you is this change: https://github.com/mileszs/wicked_pdf/compare/1.4.0..2.0.1#diff-ea9340aeb7bd0bcc5782373373980c56R9

introduced in #869 

I think maybe the deferring of loading makes it so that remotipart again get loaded first, causing render issues.

My plan for wicked_pdf version 3 is to stop mucking with render entirely, but it's a big change to the API surface.

Until then, you should be able to do something like this: https://github.com/mileszs/wicked_pdf/issues/111#issuecomment-5562812

or roll back to the working version. I do plan on working to fix this soonish, but it'll still likely be awhile before it's released unless you, or someone else, can help.

**Comment by pierre-alain-b** [comment]
First thank you for the prompt reply. I agree the only change that could explain the new behavior would be there:
https://github.com/mileszs/wicked_pdf/pull/869/files#r386040878

I don't know enough the mechanism of ActiveSupport.on_load to understand why it was needed to be compatible with Rails 6 but I agree the deferred loading could explain that remotipart is registered first.

**Comment by ryanb** [comment]
> For my culture, if someone could explain what is the interest of the deferred loading, I would appreciate. Performance?

If a reference to `ActionController::Base` is not deferred it will cause a deprecation warning in Rails 6. See: https://github.com/rails/rails/issues/36546

This is due to an issue with loading classes in an initializer which are managed by the autoloader. Classes referenced in an initializer will be lost when they are reloaded.

`ActionText` has a hook when `ActionController::Base` loads it also loads `ActionText::ContentHelper` and `ActionText::TagHelper` which are in the autoload path. This means we can't load `ActionController::Base` until after the app is initialized.

Why are the `ActionText` classes managed by the autoloader? Internally it is a Rails engine and the classes are defined in `app/models` which is in the autoload path.

**Comment by pierre-alain-b** [comment]
Thanks, I will give it a try when the new version of the gem is out! I look forward to it!
