### ISSUE TITLE
How do I adjust the header/footer height?

### ISSUE THREAD

**Issue by tsega** [mileszs/wicked_pdf#166]
I'm able to see only a part of my html header, I believe it's because the height of the margin is fixed at a lower value. So how do I ensure that all my html is shown in the PDF?

**Comment by nfriend21** [comment]
The best solution for me was to add fixed height via css on the header.  I added a class called "header" on a div which wraps the header, and gave it

height: 70px;

The reason this works best for me is because it handles the case where your PDF has more than one page.  If you only add margin-top/padding-top to the body, it wont be there on subsequent pages.  , the header will brush right up against your body content.
