### ISSUE TITLE
Large pdf generation header and footer fails

### ISSUE THREAD

**Issue by ushavimal** [mileszs/wicked_pdf#288]
I am using wicked_pdf in my app. I am able to generate small pdfs with header and footer without any problem. But when I try to generate a large pdf, it fails with header and footer. Was able to generate large files without header and footer.

Below is my options to generate pdf

    pdf = render_to_string :pdf => pdf_request.file_name,
           :layout => "pdf.html",
           :template => "shared/report",
           :wkhtmltopdf => "/usr/bin/wkhtmltopdf",
           :formats => [:pdf],
           :margin => {:top => 30},
           :header => {:html => {:template => 'shared/pdf_header',
                               :locals => {:title => pdf_request.title, :date => date}},
                               :spacing => 10},
           :footer => {:html => {:template => 'shared/pdf_footer',
                            :locals => {:run_at => TimeUtilities.sanitize_display_time(Time.now).to_s(:human)}},
                            :spacing => -4,
                            :line => true}

And the error I am getting is

    "***************\"/usr/bin/wkhtmltopdf\" -q  --header-spacing 10 --header-html \"file:////tmp/wicked_header_pdf20140219-14233-nb2cxa.html\" --footer-spacing -4 --footer-line  --footer-html \"file:////tmp/wicked_footer_pdf20140219-14233-11395q7.html\"    --margin-top 30    \"file:////tmp/wicked_pdf20140219-14233-128ah5k.html\" \"/tmp/wicked_pdf_generated_file20140219-14233-1g0xgbu.pdf\" ***************"
    2014-02-19T23:16:43Z 14233 TID-1ekr1w PdfWorker JID-34a78c3af35d06ff7ced9506 ERROR: RuntimeError: Failed to execute:
    "/usr/bin/wkhtmltopdf" -q  --header-spacing 10 --header-html "file:////tmp/wicked_header_pdf20140219-14233-nb2cxa.html" --footer-spacing -4 --footer-line  --footer-html "file:////tmp/wicked_footer_pdf20140219-14233-11395q7.html"    --margin-top 30    "file:////tmp/wicked_pdf20140219-14233-128ah5k.html" "/tmp/wicked_pdf_generated_file20140219-14233-1g0xgbu.pdf" 
    Error: PDF could not be generated!
     Command Error: Error: Failed loading page file:////tmp/wicked_header_pdf20140219-14233-nb2cxa.html?page=509&section=&subsection=&frompage=1&subsubsection=&topage=757&webpage=foobar&time=5:16 PM&date=2/19/14 (sometimes it will work just to ignore this error with --ignore-load-errors)
    Error: Failed loading page file:////tmp/wicked_footer_pdf20140219-14233-11395q7.html?page=509&section=&subsection=&frompage=1&subsubsection=&topage=757&webpage=foobar&time=5:16 PM&date=2/19/14 (sometimes it will work just to ignore this error with --ignore-load-errors)
    Error: Failed loading page file:////tmp/wicked_header_pdf20140219-14233-nb2cxa.html?page=510&section=&subsection=&frompage=1&subsubsection=&topage=757&webpage=foobar&time=5:16 PM&date=2/19/14 (sometimes it will work just to ignore this error with --ignore-load-errors)
    Error: Failed loading page file:////tmp/wicked_footer_pdf20140219-14233-11395q7.html?page=510&section=&subsection=&frompage=1&subsubsection=&topage=757&webpage=foobar&time=5:16 PM&date=2/19/14 (sometimes it will work just to ignore this error with --ignore-load-errors)
    Segmentation fault (core dumped)

    ERROR: /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/wicked_pdf-0.9.6/lib/wicked_pdf.rb:68:in rescue in pdf_from_string
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/wicked_pdf-0.9.6/lib/wicked_pdf.rb:72:in pdf_from_string
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/wicked_pdf-0.9.6/lib/pdf_helper.rb:63:in make_pdf
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/wicked_pdf-0.9.6/lib/pdf_helper.rb:32:in render_to_string_with_wicked_pdf
    /home/usha/Projects/usha-hyrax/app/utilities/reports.rb:19:in render_pdf
    /home/usha/Projects/usha-hyrax/app/workers/pdf_worker.rb:15:in perform
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/sidekiq-2.12.0/lib/sidekiq/processor.rb:49:in block (2 levels) in process
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/sidekiq-2.12.0/lib/sidekiq/middleware/chain.rb:109:in call
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/sidekiq-2.12.0/lib/sidekiq/middleware/chain.rb:109:in block in invoke
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/newrelic_rpm-3.6.2.96/lib/new_relic/agent/instrumentation/sidekiq.rb:25:in block in call
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/newrelic_rpm-3.6.2.96/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:318:in perform_action_with_newrelic_trace
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/newrelic_rpm 3.6.2.96/lib/new_relic/agent/instrumentation/sidekiq.rb:24:in call'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/sidekiq-2.12.0/lib/sidekiq/middleware/chain.rb:111:in block in invoke'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/sidekiq-2.12.0/lib/sidekiq/middleware/server/active_record.rb:6:in call'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/sidekiq-2.12.0/lib/sidekiq/middleware/chain.rb:111:in block in invoke'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/sidekiq-2.12.0/lib/sidekiq/middleware/server/retry_jobs.rb:50:in call'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/sidekiq-2.12.0/lib/sidekiq/middleware/chain.rb:111:in block in invoke'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/sidekiq-2.12.0/lib/sidekiq/middleware/server/logging.rb:11:in block in call'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/sidekiq-2.12.0/lib/sidekiq/logging.rb:22:in with_context'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/sidekiq-2.12.0/lib/sidekiq/middleware/server/logging.rb:7:in call'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/sidekiq-2.12.0/lib/sidekiq/middleware/chain.rb:111:in block in invoke'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/sidekiq-2.12.0/lib/sidekiq/middleware/chain.rb:114:in call'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/sidekiq-2.12.0/lib/sidekiq/middleware/chain.rb:114:in invoke'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/sidekiq-2.12.0/lib/sidekiq/processor.rb:48:in block in process'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/sidekiq-2.12.0/lib/sidekiq/processor.rb:87:in stats'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/sidekiq-2.12.0/lib/sidekiq/processor.rb:47:in process'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/celluloid-0.14.0/lib/celluloid/calls.rb:25:in public_send'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/celluloid-0.14.0/lib/celluloid/calls.rb:25:in dispatch'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/celluloid-0.14.0/lib/celluloid/calls.rb:125:in dispatch'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/celluloid-0.14.0/lib/celluloid/actor.rb:328:in block in handle_message'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/celluloid-0.14.0/lib/celluloid/tasks.rb:42:in block in initialize'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/celluloid-0.14.0/lib/celluloid/tasks/task_thread.rb:20:in block in create'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/celluloid-0.14.0/lib/celluloid/internal_pool.rb:59:in call'
    /home/usha/.rvm/gems/ruby-1.9.3-p194/gems/celluloid-0.14.0/lib/celluloid/internal_pool.rb:59:in block in create'

**Comment by joshuapinter** [comment]
I'm having the exact same issue with headers and footers causing large PDF generations to fail. 

My error looks like:

```bash
Error: PDF could not be generated!
 Command Error: could not retrieve system CA certificates
QEventDispatcherUNIXPrivate(): Unable to create thread pipe: Too many open files
QEventDispatcherUNIXPrivate(): Can not continue without a thread pipe
```

I also am monitoring the `/tmp` directory and nothing seems to change whilst the PDF generation is running.

Any advice or updates to this issue that may be of help?

Many Thanks.

**Comment by unixmonkey** [comment]
@joshuapinter I was going to point you at [this StackOverflow post](http://stackoverflow.com/q/25355697/23915), but I take it you've seen it, since you edited the original post yesterday.

Are you header and footer files complete html documents (with html, head, and body tags)?

**Comment by joshuapinter** [comment]
Thanks for the quick response, @unixmonkey!

Good catch with that SO post. Yeah, I saw that and made sure my header and footer were complete html files, which they are.

Smaller PDFs are just fine but once they go large it hits some sort of limit with open files. I imagine it's due to wicked_pdf or wkhtmltopdf pre/appending the header/footers, which hits a limit of how many files a single thread or process can open.

By the way, I did find the tmp files that were being generated. Both the header and footer look great and then the generated body looks good too. The body is just a single table with about 18,000 rows.

Any further suggestions?

Really appreciate your expertise on this.

**Comment by unixmonkey** [comment]
Well, in the same thread, there's a hint that you may be bumping into the file descriptor limit:

http://stackoverflow.com/a/25438941/23915

That post is by @ashkulz, who really knows `wkhtmltopdf` inside and out. On OSX, there is no /etc/security/limits.conf, but you can configure it as shown here:

http://serverfault.com/questions/15564/where-are-the-default-ulimits-specified-on-os-x-10-5

And see if that helps. If it does, be sure to let us know!

**Comment by joshuapinter** [comment]
Right on, thanks for the pointers. First step, getting it working on my dev environment. Then I'll need to make this adjustment on the servers as well.

I'm deep into it now so I'll report back when I've figured it all out.

**Comment by joshuapinter** [comment]
Hey @unixmonkey, just wanted to follow-up here with our working solution to help others get on the right path.

We've been tracking this down for the past week and came up with the following solution. For context, we're creating PDFs that are 1000s of pages long with both a header and a footer. The limits we were bumping up against were certainly not common but difficult to debug if you bounce off of them.

Two things allowed us to work around the issues:

1. I increased the open file and stack size limits of our servers by adding the following config to `/etc/security/limits.conf`:

  ```bash
*    hard nofile 1000000
*    soft nofile 1000000
*    soft stack  81920
root hard nofile 1000000 # Need these two lines as wildcards (above)
root soft nofile 1000000 # are not applied to root.
root soft stack  81920
```

2. Instead of using a S3 image in the header, we now store the image locally. Getting a header image from S3 seemed to require more resources.

You're gonna have to play with the limits to see what works with the size of the PDFs you're generating but it's surprising how high these limits have to be set to in order to prevent issues. 

Ideally, we would want to refactor wkhtmltopdf so that it does not use as many resources for appending headers and footers to a PDF document.

Thanks for your help, @unixmonkey! I hope this detail helps others in trouble.

**Comment by unixmonkey** [comment]
Thanks a ton for providing a follow-up for what works for you. I'm sure it will help others (or help me help others).

Everything seems like an edge case until it's your problem :)

**Comment by joshuapinter** [comment]
:+1: Ain't that the truth!

**Comment by crystianwendel** [comment]
@ushavimal Man, i'm facing the same issue here, large files too, but in my case i really need header and footer. When i use just texts, like:
           header: {
             center: "INSPEÇÃO E AUDITORIA TÉCNICA DOS ITENS DE\n"+
                     "SERVIÇOS",
             line: false,
             font_name: "Helvetica Neue",
             font_size: 14,
           }

I can get header and footer to work well, but i need images in my header...
You've said 

>I removed the template for header and footer and made it part of the actual template. Following is my configuration now.

How did you do that?

Thank you in advance!

**Comment by joshuapinter** [comment]
@crystianwendel Did you try my suggestions. I was able to generate very large PDFs with images in the header and a text footer. 

How big are your PDFs?

**Comment by crystianwendel** [comment]
@joshuapinter the error i'm getting from wkhtmltopdf is different from yours man, that's why i haven't tried it yet. Also, i'm running my app on Heroku, so this simple file configuration may be impossible to me without changing my servers...

Take a look in my error, if you like: https://gist.github.com/crystianwendel/c706e0086b3eccc2a530
It says `QPaintDevice: Cannot destroy paint device that is being painted`, but it work without header and footer...

**Comment by joshuapinter** [comment]
I got that error message as well. For that one I had to increase the stack size
of my servers.
If you're running on heroku, that might be difficult indeed.
If you do find a workaround make sure to post your details here. This was
painful to debug.

--
Joshua Pinter
On Fri, Aug 21, 2015 at 7:51 AM, Crystian Wendel Meneses Leão
<notifications@github.com> wrote:
@joshuapinter [https://github.com/joshuapinter] the error i'm getting from wkhtmltopdf is different from yours man, that's why
i haven't tried it yet. Also, i'm running my app on Heroku, so this simple file
configuration may be impossible to me without changing my servers...

Take a look in my error, if you like: https://gist.github.com/crystianwendel/c706e0086b3eccc2a530
[https://gist.github.com/crystianwendel/c706e0086b3eccc2a530]
It says QPaintDevice: Cannot destroy paint device that is being painted , but it work without header and footer...

—
Reply to this email directly or view it on GitHub
[https://github.com/mileszs/wicked_pdf/issues/288#issuecomment-133451204] .[https://github.com/notifications/beacon/AALCU4kq6P0TCHtMcEG1b8bWaCh74IH3ks5opzKEgaJpZM4BjVEo.gif]

**Comment by crystianwendel** [comment]
Yeah man, right now i'm working with scheduled jobs to generate my huge files, but i'm working without headers and footers, so that it won't break. If @ushavimal help me to make my layout work with header inside my main document, i don't think it will be a problem :)

I'll keep you updated, anyway! Thank you!
