### ISSUE TITLE
Text not display properly in pdf

### ISSUE THREAD

**Issue by lalitlogical** [mileszs/wicked_pdf#378]
Actual text:
![actual_text](https://cloud.githubusercontent.com/assets/3786451/5855401/ef85f5e0-a25d-11e4-8a08-561ac2f6c3ca.png)

Text in pdf:
![wicked_pdf_text](https://cloud.githubusercontent.com/assets/3786451/5855444/574c95a8-a25e-11e4-9339-bf2dd695b459.png)

**Comment by unixmonkey** [comment]
`wkhtmltopdf` will generate it's pdf using the fonts available via QT/Webkit it was compiled against, which may be different from the version of webkit (or whatever else) you are using in your web browser.

Here is a nice long thread with lots of details and tips like specifying an opentype font instead of just using one of the browser defaults, or playing with the `:zoom` setting.

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/45
