### ISSUE TITLE
I used wicked_pdf gem for my project. My project is a localize content based project. I want to write a pdf document with Unicode Bangla fonts. But It is didn't display Bangla content properly in Production server, but development mode works fine. Please help me to find out this problem solutions. 

### ISSUE THREAD

**Issue by suman5040** [mileszs/wicked_pdf#404]
Here is my production server PDF page links - 
http://107.170.201.175/orders/4
http://107.170.201.175/orders/4.pdf

Here is my projects some code snippet gists -
https://gist.github.com/suman5040/313379441c7afa5ef877
https://gist.github.com/suman5040/d4a36e3a49c708fbac0f
https://gist.github.com/suman5040/e6a067f9fa027ca1cc42
https://gist.github.com/suman5040/f7419c074bc675935a97

**Comment by suman5040** [comment]
Here is my projects some code snippet gists - 
https://gist.github.com/suman5040/313379441c7afa5ef877
https://gist.github.com/suman5040/d4a36e3a49c708fbac0f
https://gist.github.com/suman5040/e6a067f9fa027ca1cc42
https://gist.github.com/suman5040/f7419c074bc675935a97

**Comment by unixmonkey** [comment]
This is almost certainly due to your production server not having the correct fonts installed to display and render that text correctly.

`wicked_pdf` uses `wkhtmltopdf` to generate the pdfs, and `wkhtmltopdf` uses a headless x-server to fire up a virtual `webkit` browser. If that browser doesn't have the fonts necessary to display the text, then you'll have issues.

Try to include the fonts in the HTML source so they are available to the virtual browser. If you are depending on a native font, you might need to install and configure some font packages on a linux system like so: https://code.google.com/p/openesignforms/wiki/wkhtmltopdf

Let me know how it goes!

**Comment by Oymate** [comment]
@sahidursuman are you on linux?
