### ISSUE TITLE
Confused by documentation

### ISSUE THREAD

**Issue by karimmtl** [mileszs/wicked_pdf#447]
Hi,

I followed the instructions in the documentation and added wkhtmltopdf-binary to my Gemfile.

Then I run the command rails generate wicked_pdf. This generate an initializer pointing to /usr/local/bin/wkhtmltopdf which does not exist.

Do I still need to install it even if I am using wkhtmltopdf-binary? If yes what version should I install?

I am using rails 3 and bundle install installed automatically:

wicked_pdf 0.9.10 and wkhtmltopdf-binary 0.9.9.3

and here is the output of this command: bundle show wkhtmltopdf-binary
~/.rvm/gems/ruby-1.9.3-p551/gems/wkhtmltopdf-binary-0.9.9.3

Thanks

**Comment by unixmonkey** [comment]
You generally don't need the initializer if you are using one of the wkhtmltopdf binary gems.

Either delete it, or remove/comment out the `:exe_path` line.

Let me know how it goes!

**Comment by karimmtl** [comment]
It seems that the version that is installed by default does not support all the options. Here is the error that I got:
Error: PDF could not be generated!
 Command Error: Unknown long argument --javascript-delay
And this option is used in the code that I have to maintain.

What would be the best way to proceed in this case?

**Comment by unixmonkey** [comment]
javascript-delay was introduced in `wkhtmltopdf` sometime after 0.9.6, so it won't work with the `wkhtmltopdf-binary` gem, which is built with 0.9.6.

Try using the wkhtmltopdf-binary-edge gem, which ships with wkhtmltopdf 0.12.x.

Also, wicked_pdf (from rubygems) is command-compatible with 0.9.6, so if you upgrade `wkhtmltopdf`, you'll also need to update wicked_pdf to source from the master branch if you can with:

```ruby
gem 'wicked_pdf', github: 'mileszs/wicked_pdf'
```

This is still unreleased due to compatibility differences with wkhtmltopdf 0.9.6 and greater versions.

**Comment by karimmtl** [comment]
Thank you
