### ISSUE TITLE
Please make a new gem release

### ISSUE THREAD

**Issue by mattgibson** [mileszs/wicked_pdf#449]
Hi. I've just had to pin wicked_pdf to a git commit in a Gemfile because I need a fix that's only in master. There seems not to have been a release for over a year, so is there any chance the latest stable code in master could be pushed to Rubygems, please?

Thanks for all the work on the gem!

**Comment by fmh** [comment]
+1

**Comment by mogox** [comment]
Hey @unixmonkey, 

Is there something do you need help to make another release?  Looks like there are some of us interested in a new release.  I'm interested specially since at work we're upgrading to Rails 4.2.

Thank you!

**Comment by tristil** [comment]
+1

**Comment by udaykiranreddy** [comment]
+1

**Comment by tracehelms** [comment]
+1

**Comment by unixmonkey** [comment]
:boom: https://rubygems.org/gems/wicked_pdf/versions/1.0.0 :boom: 

Update your `Gemfiles` everybody!

I've also switched this project's versioning scheme to semantic versioning.
If you've been using the `master` branch, you shouldn't have any *new* issues, but you may need to check things if you are migrating from a `0.x` release.

Check the new [CHANGELOG.md](https://github.com/mileszs/wicked_pdf/blob/master/CHANGLOG.md) for details since the last gem release.

**Comment by mogox** [comment]
Thank you @unixmonkey :heart_decoration: :sparkling_heart:
