### ISSUE TITLE
Changing font-family just doesn't work

### ISSUE THREAD

**Issue by kurko** [mileszs/wicked_pdf#46]
Hey,

I'm testing WickedPDF for a while now. Everything works fine, images, CSS, JS etc. However, changing the font-family has absolutely no effect.
# The problem

For example, I can change font-size normally, but:

```
*, body {
    font-family: "Georgia", 'Times New Roman', 'Arial', sans-serif;
}
```

just doesn't work, causes no effect. It's stuck on the same font type, no matter what. Looks like it's Helvetica (I can't assess what font it is).
# How to reproduce

When I render the normal HTML (deleting the appended .pdf extension), it shows Georgia just fine. But the generated PDF doesn't. 

I'm using the latest wkhtmltopdf version. WickedPDF is updated too.

I'm on a Mac. 

Has anyone ever experienced this problem?

**Comment by imranmalik** [comment]
@brunzino, this did the trick. Thank you.
``` 
$ sudo apt-get install ttf-mscorefonts-installer
```

**Comment by ldrbrandon** [comment]
Anyone have an issue where their PDF gets rendered fine but the fonts don't get loaded or embedded in the pdf? Or worse, the text is rendered as an image instead of actual text?

I'm having a similar issue as the original post where in production, I specify 'open sans' but my rendered pdf doesn't load this font. 
Locally, it's the same except it actually uses the correct fonts, but instead of it actually being text, it renders everything as an image (upon inspecting it with acrobat)

**Comment by Myoldmopar** [comment]
@brunzino I can confirm that the mscorefonts also worked for me.  Madness... :wink:

**Comment by camdenl** [comment]
@brunzino This worked for me on my Ubuntu box using wkhtmltopdf 12.1

**Comment by prllxtchz** [comment]
> t also worked when I put quotes around sans-serif.

"it also worked when I put quotes around sans-serif." worked for me

**Comment by bitterloa** [comment]
I also had to put quotes around 'serif' or else it broke for me. This was after updating some code because it was totally working before -- the below worked for me (i wanted a serif font, *not* sans-serif):

`font-family: 'serif';`

**Comment by pastullo** [comment]
+1 on the 
`sudo apt-get install ttf-mscorefonts-installer`

thank you @brunzino
