### ISSUE TITLE
Guys, can't make it work

### ISSUE THREAD

**Issue by GoodJob** [mileszs/wicked_pdf#462]
I'm not so expert in Rails, so I can't understand the essence of wicked_pdf how it saves or renders the file? I have done all steps provided - no errors, but still can't get file saved or rendered. Maybe you can provide some kind of code in the instruction which will be able to do simple test with the result. Because I see all lot of tricks, but not the essence how to make it work. 

Should it be saved somewhere or rendered? Can't find information about that.

Sorry guys. Thank you for helping!

**Comment by unixmonkey** [comment]
Did you close this because you got it working?

In the simplest case, once `wicked_pdf` and `wkhtmltopdf` are installed, you should be able to do something like this from any controller action:
```ruby
class ThingsController < ApplicationController
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "file_name"   # Excluding ".pdf" extension.
      end
    end
  end
end
```

And create a corresponding view in `app/views/things/show.pdf.erb` and write your view in HTML.

If you watch the Rails console output as it attempts to generate a PDF, it may give you a clue to why it is not working for you.

Let me know how it goes!
