### ISSUE TITLE
Slow with Thin?

### ISSUE THREAD

**Issue by daninfpj** [mileszs/wicked_pdf#475]
I'm generating a few PDFs in a batch, but every three files it takes longer than the others (more than 3 minutes, whereas the other files take seconds). That happens every time: so two are generated instantly, then one takes a while, then other two instantly, one take a while…

If I generate those that take longer individually, they're generated instantly as well.

I just ran the same thing on my development environment which is exactly the same setup as production, except that it runs just one Thin server (normal rails start and accessed via port) instead of three (and acts as an Apache Proxy) and all the files are generated instantly.

Any ideas?

**Comment by unixmonkey** [comment]
Here's how I can picture that happening:

You hit your PDF generation endpoint on `server 1`, then *it* hits `server 2` and `server 3` to load some stylesheets and javascript files in the PDF template, and now you have no more servers available to finish the document generation...until either the `thin` or `wkhtmltopdf` timeout is reached, and possibly some stylesheet or JS never loads, but the document does get generated.

Please check and make sure you aren't loading any assets over HTTP/HTTPS. You can use the `wicked_pdf_*_tag` helpers to load your assets over the `file://` protocol, or the `wicked_asset_base64` helper to base64 encode your assets inline in the HTML source before it gets PDF-ified.

Other than that, it sounds like it could be an intermittent problem that only *seems* like its every 3rd thing, because it hits a memory limit and pauses to do garbage collection or something like that, which seems less likely.

Please let me know if any of this helps or not.

**Comment by daninfpj** [comment]
@unixmonkey You're right, that's exactly what was happening. There was a single JS file that was loading over HTTP.

Thanks a lot.

**Comment by unixmonkey** [comment]
Awesome, I'm glad to help!
