### ISSUE TITLE
Very slow page rendering even with empty PDF

### ISSUE THREAD

**Issue by jpmoral** [mileszs/wicked_pdf#486]
I have a controller action like so:

```
def show
    foo = Foo.find params[:id]

    respond_to do |format|
      format.pdf do
        pdf_name = foo.name

        render :pdf => pdf_name,
                :page_size => 'A4',
                :layout   => 'pdf.haml',
                :margin => {:top   => 45,
                           :bottom => 20,
                           :left   => 10,
                           :right  => 10 }
      end
    end
  end
```

and a `pdf.haml`:

```
!!!
%html
  %head
    Foo
```

rendering this in development takes upwards of 30 seconds.  I use `wkhtmltopdf-binary` 0.9.9.3 and `wicked_pdf` 0.11.0.  I've tried `wicked_pdf` 1.0.3 and `wkhtmltopdf-binary-edge` (uses 0.12.2.1) with similar results.

Can anyone suggest a fix or troubleshooting steps?

**Comment by unixmonkey** [comment]
That is unusually long. Is that truly the entire view file?

It sounds to me like either `wkhtmltopdf` is having trouble parsing an incomplete HTML document (missing a body).

Or it could be somewhere in the view or layout, it is requesting another asset or route (for an image or stylesheet?), which in development mode requires a multi-threaded dev server (like Puma), and is one of the reasons the `wicked_pdf_*` helpers exist; to circumvent that by requesting file contents from the file system instead of over HTTP.

You could also try version 1.0.4 of the gem, as it contains some fixes for the asset pipeline that may help.

**Comment by jpmoral** [comment]
@unixmonkey

The real template is not as bare, I just removed stuff as a troubleshooting step.  You've given me some ideas to explore, I'll post again when I've tried them, thanks.

**Comment by beydogan** [comment]
I'm having the same issue and figured out that its related to `asset_data_base64` in layout. It takes long time to generate asset data and it generating them in every request. Some kind of caching is needed there.
