### ISSUE TITLE
Compatibility issues in production with wkhtmltopdf-binary

### ISSUE THREAD

**Issue by Exanimous** [mileszs/wicked_pdf#527]
I have recently experienced issues getting wicked_pdf to work in production mode.

In particular, supplying one or more of the following arguments will cause the pdf render to fail.

    cover: render_to_string('reports/cover.pdf.erb'),

this will fail with the following error (it will however work on a blank value such as '', suggesting the parameter is accepted just not the argument.

    Error: Failed to execute: ["/home/mja/.rvm/gems/ruby-2.3.0/bin/wkhtmltopdf", "-q"] 
    Error: undefined method `<' for nil:NilClass

In addition.  Any use of the toc: arguement (even an empty hash) will cause the same above error.

I have also noticed that assets will not be correctly displayed by wicked_pdf using this binary unless 
config.assets.compile = true.

Note that above issues only occur in production, making the issue deceptively difficult to identify.

gem 'wicked_pdf', github: 'mileszs/wicked_pdf' (both branches have same issue).
gem 'wkhtmltopdf-binary'

I have also tried manually installing the wkhtmltopdf from the binaries (0.12.2.1) and statically setting the exe path, but the same issue is present.

Rails 4.2.6
Ruby 2.3.0

**Comment by Exanimous** [comment]
I was actually able to solve the two above issues by using the wkhtmltopdf-binary-edge', '~> 0.12.3.0 derivative gem.  The only problem is it seems to have removed a lot of the useful toc: options like depth etc.

I was not able to find another way around these issues.

Is there any reason why this newer release is not documented in the readme?

**Comment by unixmonkey** [comment]
I think the primary reason so far is that `wkhtmltopdf-binary-edge` only includes binaries built against Ubuntu and OSX, and will not work on other flavors of Linux (including Heroku), and totally excludes Windows support.

There are also semi-major differences in command syntax and options available between `wkhtmltopdf` releases. Some options only work on older versions, and some only on newer.

Regarding `config.assets.compile`, https://github.com/mileszs/wicked_pdf#asset-pipeline-usage shows that you should add assets necessary for PDFs to the `config.assets.precompile` array (instead of recompiling everything every request).

Pull requests are welcomed, especially to the README and wiki. Anything that could things clearer would be appreciated.
