### ISSUE TITLE
Auto-appending "css" extension breaks remote URLs

### ISSUE THREAD

**Issue by sethvargo** [mileszs/wicked_pdf#556]
Hi there,

I noticed that it's not possible to specify a remote URL that's a CSS resource unless that URL ends in CSS. This is especially problematic for Google Fonts, since they do not end in such an extension.

I believe this is being caused by [this line here](https://github.com/mileszs/wicked_pdf/blob/f133eb05c43a4614a174d1ae2275077f0ca0cac0/lib/wicked_pdf/wicked_pdf_helper/assets.rb#L17), which the library decides to append "css" to the extension (fwiw, it does the same for js too).

If I understand correctly, this is because of how the local asset search works, but I don't think the postfixing should be applied to remote paths.

**Comment by unixmonkey** [comment]
Patches accepted, provided they don't break backwards compatibility without a deprecated version first.

How do you think we could handle the transition if we introduced a deprecation?

My initial thought is that we could warn every time `add_extension` is called warning it will go away in a future release.

I'd like to note, however, that in your situation, you should probably be using the normal `stylesheet_link_tag` instead of `wicked_pdf_stylesheet_link_tag`. The major point of using the `wicked_*` versions is to speed up PDF rendering by providing local filesystem resources so the headless browser doesn't have to wait for HTTP, but with a remote resource, it has to anyway.

**Comment by sethvargo** [comment]
Would it be unreasonable to not post-fix if the URL is absolute and remote? I don't think that would break backwards-compat, would it?
