### ISSUE TITLE
Not working for API inherited ApplicationController in Rails

### ISSUE THREAD

**Issue by sposmen** [mileszs/wicked_pdf#616]
First, thanks for this gem.

How to reproduce:
1. Generate a new rails application as API
    `rails new --api`

2. Setup the gem according to current Readme

Actual result:
PDF Error

Expected result:
Generated PDF

Inheriting  from API doesn't give enough variables to render PDF's like from Base

To correct the issue temporary could be changed the file `application_controller.rb` from 
```ruby
class ApplicationController < ActionController::API
```
to 
```ruby
class ApplicationController < ActionController::Base
```

**Comment by unixmonkey** [comment]
Hm. This gem registers itself in `ActionController::Base` [here](https://github.com/mileszs/wicked_pdf/blob/master/lib/wicked_pdf/railtie.rb#L12).

Instead of your workaround, I'd advise doing what the railtie does in your own app something like this:
```ruby
class ApplicationController < ActionController::API
  prepend PdfHelper
  include WickedPdfHelper::Assets
end
```

If that works, it should be a pretty easy to also register with `ActionController::API` if it is defined in that railtie as well.

Pull requests are appreciated, though I'm not 100% sure API users would want WickedPdf to self-register. Maybe a note in the README would be more appropriate?

Others that come across this issue: What do you think?

Let me know how it goes!

**Comment by estiens** [comment]
hmmm, this isn't working...wondering if anyone else has a fix? It's the prepend call that seems to be the problem

**Comment by unixmonkey** [comment]
In short, API controllers only respond with JSON or XML, otherwise `render` and `render_to_string` will only return a single space string (`' '`).
Create a new controller that inherits from `ActionController::Base` for your PDF-rendering endpoints.

I wasn't aware of this when I initially responded to this thread, but it's been better explained in a later issue, so I'm closing this one to reference that one.

Please refer to #652
