### ISSUE TITLE
couldn't find HOME environment -- expanding '~'

### ISSUE THREAD

**Issue by TechFounder** [mileszs/wicked_pdf#621]
I'm getting this error ```couldn't find HOME environment -- expanding '~'``` when i try to create a pdf. This error seems to only appear on the staging/production environment. Not local. 

Furthermore, this only affects previously created items but not newly created. Anyone have an ideas on a fix? Could it be some server setting?

**Comment by BeenaShetty** [comment]
I am also getting the same error on production. Can someone help ?

**Comment by unixmonkey** [comment]
This is happening because it's hitting [this chunk of code](https://github.com/mileszs/wicked_pdf/blob/master/lib/wicked_pdf.rb#L333-L342)

if you set `exe_path`, it won't need to look for it. You can do that with an initializer like this:

```ruby
if Rails.env.production?
  WickedPdf.config = {
    exe_path: /usr/local/bin/wkhtmltopdf # or wherever it actually is in production
  }
end
```

Closing this issue. We can reopen if you continue to have issues. Let me know how it goes.
