### ISSUE TITLE
Cannot render PDF from a controller inheriting from ActionController::API in a Rails API-only project

### ISSUE THREAD

**Issue by teoh770** [mileszs/wicked_pdf#652]
Gem itself can generate the PDF file; however when I try to view the generated PDF file, it shows PDF error. Any idea to solve this issue? Thanks.

**Comment by unixmonkey** [comment]
Can you share more about how you are generating the PDF? Can you upload the PDF file somewhere I could check it out?

**Comment by teoh770** [comment]
Hi, 

This is my code use to generate the PDF.
`# GET /case/case_pdf/:id
    def case_pdf
      respond_to do |format|
        # format.html
        format.pdf do
          puts 'hello'
          render :pdf => "report", template: "cases/case_pdf.html.erb"
        end
      end
    end`
attachment is the generated PDF file.
[download.pdf](https://github.com/mileszs/wicked_pdf/files/992166/download.pdf)

**Comment by unixmonkey** [comment]
Thanks for the extra info. The generated PDF isn't a PDF, but a 1 byte file. Blank with only a single space in it, if you were to open it in a plain-text editor. This tells me something has gone wrong, but the file has still been created and served. I suspect there is either an issue with `case_pdf.html.erb`, or your install of `wkhtmltopdf`.

Does it work if you remove the `template` argument?

**Comment by teoh770** [comment]
Thanks for the reply. It still cannot work after I remove the template argument. However, it work in rails normal web project. FYI, current project is rails api project.

**Comment by unixmonkey** [comment]
I generated a Rails 5.1 api only project, and found `respond_to` isn't defined on controllers, but you can get it back by including `ActionController::MimeResponds` into your controller.

In API-only mode, `ApplicationController` inherits from `ActionController::API` instead of `ActionController::Base`. This is a slimmed-down controller that doesn't handle rendering of HTML or sending of files quite the same, and rendering anything except XML or JSON returns only an empty string.

I would suggest adding a separate controller for your PDF-serving that does inherit from `ActionController::Base` that can operate as normal with `wicked_pdf`.

Let me know how it goes!

**Comment by teoh770** [comment]
Hi, thanks for the reply. I manage to get `wicked_pdf` to work in the controller that inherit from the `ActionController::Base`.

**Comment by unixmonkey** [comment]
Great!

**Comment by tottivega** [comment]
Just want to add something in case anybody finds this issue on a Rails API using rails 5.

After creating the controller that inherits from ActionController::Base. You might encounter the error:

ActionView::Template::Error (undefined method `assets' for #<Rails::Application::Configuration:0x00007fad05adb600>
Did you mean?  asset_host)

This can be fixed by uncommenting the line require "sprockets/railtie" from condif/application.rb

**Comment by Babbz75** [comment]
@unixmonkey if I want to just generate a pdf to store in active storage and not return it in a view would I still need to change my controller inheritance?

Currently I'm storing it in the public folder but running into the same problem when trying to open it.
