### ISSUE TITLE
i18n Support

### ISSUE THREAD

**Issue by przbadu** [mileszs/wicked_pdf#665]
Does, wicked_pdf support i18n, because right now it is broken for me. If it has a support for i18n, please let me know how can I configure it?

**Comment by unixmonkey** [comment]
What isn't working for you? Wicked PDF turns HTML into a PDF, if the HTML is in another language, the PDF should be, too.

If you are having trouble with character encoding, make sure you have a character set in a meta tag in your pdf views or layouts:

```html
<meta charset="utf-8" />
```

If you are having trouble with fonts, make sure you have them installed to the system.

If you are using a Javascript library to translate (like I18n.js), make sure it is being loaded correctly.

Closing for now, since this isn't an issue with the gem, but please keep me posted!
