### ISSUE TITLE
Not same format in development and production

### ISSUE THREAD

**Issue by rbUUbr** [mileszs/wicked_pdf#670]
Hi! I found next trouble: 
On my computer ( in development and production modes ) wicked_pdf generate me doc with correct format:
![screenshot from 2017-07-12 17 34 05](https://user-images.githubusercontent.com/18901132/28125383-20260382-672f-11e7-8694-9cfa453bc6c7.png)
Svg checkbox is left from text
But on our server something bad with it:
![screenshot from 2017-07-12 16 21 10](https://user-images.githubusercontent.com/18901132/28125430-441025ac-672f-11e7-94ff-028ad7c6d42f.png)

Code:

> Controller

```
respond_to do |format|
      format.html { render layout: 'briefs' }
      format.pdf do
        render pdf: "file_name_of_your_choice",
          template: "submitted_briefs/show_pdf.pdf.erb",
          layout: 'briefs',
          disable_javascript: true,
          locals: { submitted_brief: @submitted_brief }
      end
    end
```

> View

```
<%= inline_svg 'form_controls' %>
<main class="new-root">
  <header class="header">
    <a href="/" class="logo" id="t"><%= wicked_pdf_image_tag "agente_logo.svg", id: "t" %></a>
  </header>
```

Have a good day!

**Comment by unixmonkey** [comment]
This looks like it could be a css issue between screen and print media, or possibly a media query for the size of the virtual browser, use `show_as_html` to view your HTML in Chrome in two different tabs or windows, then open the inspector and change what stylesheet is used in one of them.

You can do that by right clicking any page > Inspect > click on the "three-dots" menu in the top right corner > More Tools > Rendering Settings > Emulate CSS media > print, or toggle between what's available to track down where the difference is.

It is also possible that the font size is just a bit bigger in production (due to installed fonts on your production server), causing it to flow down. Try tweaking that, or specifying a size.

You could possibly also experiment with setting the Wicked PDF `zoom` rendering option.

Let me know how it goes!

**Comment by rbUUbr** [comment]
Found some temporary solution. Added in my scss file next: 
```
svg{
  float: left;
  display: inline;
}
```

**Comment by unixmonkey** [comment]
Great. Thanks following up!
