### ISSUE TITLE
PDFs are blank in Rails production mode using Middleware request

### ISSUE THREAD

**Issue by mglenn** [mileszs/wicked_pdf#681]
I've set-up Wicked PDF and successfully requested PDFs of application pages using the Middleware and appending .pdf to the URL. This works consistently in development and staging environments including our staging server on Heroku. In production this almost never works. It sometimes works on the first request but subsequently fails only occasionally working after several reload or perhaps waiting and reloading.

Reconfiguring my local dev environment to run in production mode produces the exact same result as our production server.
production.rb and staging.rb are identical in their configuration settings. Both are set to compile assets and precompile is the same. All environments are Rails 4.2.9 with Ruby 2.3.3. No errors are present in the logs.

I know that the PDF is sort of generating as it has multiple page. Viewing in a text editor I see %PDF-1.4 as a prefix and %%EOF as a suffix. The pages are just blank.

Wicked PDF doesn't appear to have any switches in the source code for production versus other environments so I'm not sure what could be causing this. 

I've tried wkhtmltopdf-binary and wkhtmltopdf-binary-edge as well.

**Comment by unixmonkey** [comment]
One of the issues with the middleware approach, is it converts asset requests (javascript, stylesheet) into absolute references, for example `/stylesheets/application.css` becomes `https://yourhost.com/stylesheets/application.css`, which means `wkhtmltopdf` needs to individually fetch those resources from your server to assemble your PDF, and it may be timing out (especially if you are using a single-threaded web server, your requests may be queued instead of responding, leading to a deadlock or timeout).

You can get around this in many cases by using the `wicked_asset_base64` helper.

Because of Rails fingerprinting, you may still need to add your assets to [the precompile list](https://github.com/mileszs/wicked_pdf#asset-pipeline-usage). Usually in `config/initializers/assets.rb`.

Because you can reproduce this locally, try removing all layout (`render layout: false`) and external resources (CSS/JS/images), and try, then start adding them back in until something breaks and report back.

Good luck, and keep me updated!

**Comment by mglenn** [comment]
It was Google Analytics. It was the one external asset that I hadn't forced https and it stayed with the protocol relative url prefix "//" to match the parent page as per this blog post: https://reinteractive.com/posts/257-protocol-relative-urls

Is there a better way around protocol relative asset URLs when using the middleware method or do all these URLs need protocols specified? 

Thanks for answering so fast David!

**Comment by unixmonkey** [comment]
Not 100% sure, but I think protocol-relative `//`-starting assets could perhaps be handled around [this line](https://github.com/mileszs/wicked_pdf/blob/master/lib/wicked_pdf/middleware.rb#L46).

PRs welcome.

**Comment by mglenn** [comment]
Unfortunately my particular issue was in a JS file that doesn't expose the URL within an HTML href or src tag and would need to be evaluated at runtime.

I tracked it upstream to an issue that needs to be fixed in QT and reported in [QTBUG-46440](https://bugreports.qt.io/browse/QTBUG-46240). Most discussions around this issue seem to be fine converting references to HTTPS since it's becoming more widely supported. I think it's still a bug as all browsers support it but I'll re-focus on the QT project and leave this here for reference.

Thanks.
