### ISSUE TITLE
High Resolution Images Rendering problem (Darker than original)

### ISSUE THREAD

**Issue by 91juhwang** [mileszs/wicked_pdf#699]
Hi, 

I have issues rendering images while generating a PDF. 

Everything works great if the image size is small or mediocre. However, for high resolution image(ex. 3000px by 2500px) it becomes a darkened photo. 

The same image works fine with just HTML, but becomes dark in PDF.
Low resolution images are fine in both HTML & PDfs.

Below is the code that I used
```ruby
  def save_page(args)
    ac = ActionController::Base.new()
    pdf = ac.render_to_string(
      pdf: create_pdf_file_name(args),
      locals: {
        :@collateral => @collateral,
        :@collateral_object => @collateral_object,
        :@agent => @agent,
        :@listing_object => @listing_object,
        :@buyside_object => @buyside_object,
        :@buyside_params => @buyside_params
      },
      page_size: decide_page_size(args),
      page_width: decide_page_width(args),
      page_height: decide_page_height(args),
      template: template_location(args[:page_number], args[:collateral_type]),
      orientation: args[:orientation],
      encoding: 'UTF-8',
      margin: { top: 0,
      bottom: 0,
      left: 0,
      right: 0 },
      disable_smart_shrinking: true,
      dpi: 300
    )
    File.open(decide_save_path(args), 'wb') do |file|
      file << pdf
    end
  end
```
After saving few pages with the above method, I've used `combine_pdf` to combine multiple pdfs into one.
Since when the image quality is low or mediocre works fine, I think it is more of a problem in actual PDF creation process. 

I've attached the sample to display what I meant by it. 
Any guidance for this issue will be appreciated!

Thank you. 

Original:
![screen shot 2017-10-25 at 4 35 05 pm](https://user-images.githubusercontent.com/19839784/32022035-379046c4-b9a3-11e7-9587-9a8bbe57cf87.png)

Rendered PDF:
![screen shot 2017-10-25 at 4 40 09 pm](https://user-images.githubusercontent.com/19839784/32022036-379d43b0-b9a3-11e7-8e22-c16106be0e47.png)

**Comment by unixmonkey** [comment]
It'd be good if you could isolate the issue and see if that is the case before using `combine_pdf`.

That said, I think you may be seeing a variation of [this issue](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2208), which is potentially fixed in `wkhtmltopdf` 0.12.3 or later (0.12.4 is latest stable right now).

Please download and try out a newer version of `wkhtmltopdf` from [here](https://wkhtmltopdf.org/downloads.html#stable) and see if it helps with your issue.

If that doesn't work, maybe run your images through a pre-processor on upload like [Paperclip](https://github.com/thoughtbot/paperclip) to get a reduced-size version to use for making PDFs.

Let me know how it goes, and what works or not!

**Comment by 91juhwang** [comment]
Hi!
Thanks for the quick response!

I am currently using 0.12.4, and I am using `background: url('web-address-to-image`)`,to get the high resolution image directly to the css. 

I also tested without combine_pdf, but the issue was still there, which indicates that it is not a problem with combine_pdf. 

The low image quality & regular images work fine and generates perfect PDF, which I am sure it's something to do with the high definition images. We really would like to use high definition images instead of the reduced-size version. 

This is the link to the high definition image that I am using: [image]('https://images.datahubus.com/core_data/image/file/59e506/e7f50c/fd0324/f29cf3/3c496229-14b7-4530-8ef2-7e4273d9a20e_C72A5718.jpg)

This said, do you have any other ideas why this would be happening?

**Comment by 91juhwang** [comment]
By the way, thank you so much for providing an awesome software and being up to date with it!

**Comment by unixmonkey** [comment]
I was able to easily reproduce your issue with `wkthmltopdf` 0.12.4 on my system, and provided that reproduction info to the project maintainer in the issue referenced above.

I'm not sure what you can do at this point other than adding a transparent div over the top of the images to pre-adjust the color, so that the output is closer to expected.

Too bad `-webkit-filter` doesn't work with `wkhtmltopdf`, or that would be a good solution, too.

**Comment by 91juhwang** [comment]
Thank you very much. 
Hopefully the maintainers see and resolve the issue quickly.

**Comment by 91juhwang** [comment]
Hi!

Found the solution, so here I am to share. 

The large photo had the following color profile: ProPhoto RGB. Once it is converted to sRGB, it works fine.

**Comment by unixmonkey** [comment]
Can you share how you are achieving the conversion programmatically?

**Comment by 91juhwang** [comment]
@unixmonkey 
Running the imagemagick command, `magick before.jpg -profile sRGB2014.icc after.jpg` has converted the color_profile to sRGB format.
sRGB2014.icc file(can download online) is needed to convert to sRGB format.
