### ISSUE TITLE
Page number showing wrong

### ISSUE THREAD

**Issue by abhidsm** [mileszs/wicked_pdf#727]
Hi,

We are getting wrong page number in the PDF generated. The total page is 73 but in the footer of the last page is showing 73 of 72. 

So the total page is calculated as 72, but due to some page break or something, there are 73 pages.

I am attaching the last page screenshot below:

![wicked_pdf_page_number_issue_edited](https://user-images.githubusercontent.com/397260/37401294-9e9dbba8-27ad-11e8-840f-9d2963571f2c.png)

We are using the same code shared in the README: https://github.com/mileszs/wicked_pdf#page-numbering

Please help us to resolve this issue.

**Comment by unixmonkey** [comment]
Is only the last page wrong, or does it skip a number somewhere in the document?

This is just javascript to count the pages, it's a little dense, but you could append the contents of `x` to the page to debug, or you could use the plain-text version, since I don't see you using any fancy html or styling with:

```ruby
render pdf: 'mypdf', footer: { right: 'Page [page] of [topage]' }
```
Let me know how it goes!

**Comment by unixmonkey** [comment]
Any luck?

**Comment by akshaysajeevan** [comment]
Hi @unixmonkey , we did try this approach, now we go get the correct page number but the calculated total page number is coming wrong. 
![screenshot from 2018-08-10 16_41_21 1](https://user-images.githubusercontent.com/24456311/43955275-fdf4a150-9cbc-11e8-8a09-876745e026b2.jpg)

**Comment by unixmonkey** [comment]
Can you update `wkhtmltopdf` to the latest version `0.12.5` and check that.

It seems this is a known and somewhat common issue with `0.12.4` and earlier.

You may want to check the effect of `disable_smart_shrinking`, and try without custom webfonts, or check out [this issue](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1771) for tips if you are still having issues.

Closing because this isn't related to `wicked_pdf`, but please let me know how it goes anyway!
