### ISSUE TITLE
failed to download ?

### ISSUE THREAD

**Issue by dunods** [mileszs/wicked_pdf#732]
anyone having an issue with failed to download on google chrome ? or network error

**Comment by kirylpl** [comment]
@unixmonkey Have the same issue. PDF actually generated, but the issue is that Chome PDF Viewer sometimes offers to download with different file name from file_name described in render pdf method.
<img width="940" alt="Screenshot 2020-12-22 at 11 45 27" src="https://user-images.githubusercontent.com/3589618/102868419-36f20a00-444b-11eb-9be4-9b4bc64fd2a3.png">

**Comment by kirylpl** [comment]
I resolved "Failed - Network error" issue by removing `method: :get` from link_to.
I found that PDF file_name broken by authenticity_token existence in params somehow.
