### ISSUE TITLE
issue when running rails g wicked_pdf if Rails app is called wickedPdf

### ISSUE THREAD

**Issue by nand09** [mileszs/wicked_pdf#802]
I was giving a test to wickedPdf when I created a new rails project and named it wickedPdf. I installed the gem successfully but when I wanted to run the `rails generate wicked_pdf`, I received a `WickedPdf is not a module (TypeError)`.

I don't feel this is a big issue, but I would like your thoughts on this.

**Comment by unixmonkey** [comment]
Because you named your project `wickedPdf`, Rails named your application class namespace (in `config/application.rb`) `WickedPdf`, which conflicts with the name of the gem.

You should be able to find and replace all instances of `WickedPdf` (in your app code) to something more relevant to your app (like WickedPdfTest?) and get things working again. I don't think this is something we should address within the gem.
