### ISSUE TITLE
Debian 9 font-size issue

### ISSUE THREAD

**Issue by fessio-software** [mileszs/wicked_pdf#825]
## Issue description
Font-size set in CSS doesn't work on Debian 9. On Ubuntu 18.04 with the same gem and wkhtmltopdf versions works fine. 

## Expected or desired behavior
Find a solution quickly

## System specifications
**wkhtmltopdf** - I have tried 0.9.6 (doesn't work), all from 0.12.0-0.12.5
**wicked_pdf** - 1.2.2
**Ruby** - 2.5.5
**Rials** - 5.0.7.2

## Examples:

[debian.pdf](https://github.com/mileszs/wicked_pdf/files/3061057/debian.pdf)
[ubuntu.pdf](https://github.com/mileszs/wicked_pdf/files/3061058/ubuntu.pdf)

```html
 <!DOCTYPE html>
 <html>
 <head>
 	<meta charset="utf-8" />
 	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
 </head>
 <body>
 	<div style="padding-top: 15%;text-align: center;">
 		<h1 style="font-size:100px">18/2019</h1>
 		<h2>TRW</h2>
 		<h5>TRW przekładnie</h5>
 		<p>09-04-2019</p>
 	</div>
 </body>
 </html>
```

**Comment by unixmonkey** [comment]
@fessio-software How are you installing `wkhtmltopdf` on Debian?

I would suggest you try installing the version available on https://wkhtmltopdf.org/downloads.html rather than the one available from the package manager to see if that makes a difference.

You may want to check for a solution to this on the `wkhtmltopdf` issue tracker and cross-post this there if you still can't find anything:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues

Though, if you do find a solution, I would appreciate it very much if you could update this issue.

**Comment by fessio-software** [comment]
I have found a solution: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2193#issuecomment-136962264

Thanks!
