### ISSUE TITLE
show_as_html is not showing header and footer

### ISSUE THREAD

**Issue by vincentlkl** [mileszs/wicked_pdf#874]
Has anyone encountered that after setting the `show_as_html` as true it only shows the body of the pdf but not the header and footer.

Bellow is how my script looks like
```
render pdf: object_no,
           layout: false,
           orientation: orientation,
           page_size: 'A4',
           show_as_html: params.key?('debug'),
           header:  {
             spacing: 3,
             content: render_to_string({
               template: header_template, locals: { print_type: print_type }
             }),
           },
           footer:  {
             content: render_to_string({
               template: footer_template, locals: { print_type: print_type }
             })
           }
```

**Comment by unixmonkey** [comment]
That's expected. Headers and footers are rendered as separate (thin) HTML documents, then overlaid on the tops and bottoms of each PDFd page by the `wkhtmltopdf`.

The browser doesn't know how to render 3 separate HTML documents on one webpage and account for page sizes and margins. `show_as_html` is intended as a debugging tool, but won't look exactly the same as the resulting PDF.

**Comment by vincentlkl** [comment]
ok noted thanks a lot.

**Comment by vincentlkl** [comment]
@unixmonkey if we're investigating a font/spacing issue with the header, what's the best way to debug then?

**Comment by unixmonkey** [comment]
Is it that the kerning between certain letters is uneven? 

Try playing with the `:zoom`, `:disable_smart_shrinking`, `:dpi` or `:lowquality` values.
Is it that a font isn't loading correctly (or is loading a fallback system font). Try using quotes around the font like `src: url('somefont')` instead of `src: url(somefont)`

If it's a TTF, try converting it to an OTF.
If it's a long font name, try renaming your font-family names to not share any matching words and/or be less than 8 chars.

If the header and footer aren't being shown at all, or are cut off, try changing their background-color with CSS, and playing with the `:margin` and `:padding` settings.

Let me know how it goes, and if you still need help, paste a screenshot or some code to help me figure out what issue you are having.

**Comment by raoulalwani** [comment]
@unixmonkey Thanks for the robust tips! 

> Is it that a font isn't loading correctly (or is loading a fallback system font). Try using quotes around the font like src: url('somefont') instead of src: url(somefont)

We suspect this is the cause -- basically, when deploying the application on other servers, there are obvious visual differences in the font of the output PDFs -- this causes the alignment of all the elements on the PDF get shifted and some key information no longer appears (likely pushed off-screen due to the font difference/padding)

I've run `fc-list` on the working instances and on the new servers, and there's a difference in font lists. Rather than code splunk and install everything, the idea was to inspect the specific font on the "correct" instance and "wrong" instance, and just make sure that font installation happens as part of our server provisioning scripts. Hence the need to `view_as_html` to see what specific font the wrong server was referencing.

We'll try the `font src` option and post our findings here, but any other suggestions on isolating the font or debugging along those lines is appreciated.

**Comment by unixmonkey** [comment]
Yes, if you are planning on using one of the system fonts, you should make sure it's installed on each system, or use a web-font instead.

There's some notes on installing fonts in #46, #456 and #496

**Comment by raoulalwani** [comment]
Just a quick update for anyone who might stumble upon this at a future date:

We were completely over-complicating things. The base issue was: we had PDFs generated in our existing app, and it works fine on our existing server instance. When using Ansible to provision a new server instance of our app, the PDF output was visibly different, causing some information to not render correctly. 

We guessed it to be a font issue, but how to narrow it down to the specific font? You can "inspect" a PDF manually using Adobe Reader. Just open the file in Adobe, click File > Properties > Font, and it'll show you what fonts are being used there. Comparing our correct and incorrect PDFs, the listed fonts were different. We had wandered off track trying to "debug" the PDF using show_as_html, inspect elements, etc etc.

In our case, it was two issues: the correct font wasn't installed on the new server, and we were not correctly specifying the font in the CSS.

Wrong version:
```
body {
  font-family: sans-serif;
  font-size: 11px;
  line-height: 13px;
}
```

Correct version
```
body {
  font-family: "Nimbus Sans L" sans-serif;
  font-size: 11px;
  line-height: 13px;
}
```

So, we updated the CSS file to be more specific, and added the font installation line to our Ansible script, and it all works perfectly well now. 

Thanks @unixmonkey for the tips!
