### ISSUE TITLE
no implicit conversion of nil into a string

### ISSUE THREAD

**Issue by henron1** [mileszs/wicked_pdf#886]
```
2.5.1 :001 > @pdf = WickedPdf.new.pdf_from_url(`localhost:3000/admin/people/43743/roles/801/agreements/22982`)
bin/rails: No such file or directory - localhost:3000/admin/people/43743/roles/801/agreements/22982
[wicked_pdf]: ["/Users/lambda_school_loaner_98/.rvm/gems/ruby-2.5.1@backlit/gems/wkhtmltopdf-binary-0.12.5.1/bin/wkhtmltopdf", nil, "/var/folders/1l/2lhmsrbj72l92b4t2vs65vq40000gn/T/wicked_pdf_generated_file20200207-1866-1qbark6.pdf"]
Traceback (most recent call last):
        1: from (irb):1
RuntimeError (Failed to execute:)
["/Users/lambda_school_loaner_98/.rvm/gems/ruby-2.5.1@backlit/gems/wkhtmltopdf-binary-0.12.5.1/bin/wkhtmltopdf", nil, "/var/folders/1l/2lhmsrbj72l92b4t2vs65vq40000gn/T/wicked_pdf_generated_file20200207-1866-1qbark6.pdf"]
Error: no implicit conversion of nil into String
```

Anyone have an idea what the missing parameter is in the array? The second one is coming back as nil and I'm not sure if I'm supposed to be passing in another argument with the url.

**Comment by unixmonkey** [comment]
@henron1 

I think the `nil` there is where the URL would be if it were correctly formed.
The array you are looking at is how wicked_pdf builds the command, and the parts are joined on the shell.

A few issues I see with this:

The use of backticks instead of single or double-quotes around the URL. In Ruby, this tries to run a command as if called with `exec()`, which would have the return value of `nil`. This could have been an auto-formatting on paste mistake though, but maybe not.

The URL passed is not a fully qualified URL, as in, it doesn't start with `http://` or `https://`, so it won't be found even if it worked

By calling out to `localhost:3000` from inside your Rails app, you may see an infinite wait, because the current request that you are building the PDF from will execute the command, which kicks off a new request to your local web server, but many Rails development servers can only do one request at a time, and since the first request is still waiting for the PDF to finish rendering, and the PDF is waiting for the HTML to come back, they end up in a deadlock, each waiting for the other to finish first. You can address this by using multiple web threads locally like it would in production by adding and configuring the `puma` web server, or something like it.

Instead, you may want to look into other ways of getting the HTML into `wicked_pdf`. From inside your app, you can usually `render` a template or partial. I have a whole bunch of examples on how to do both simple and strange things in my [wicked_pdf_issues pages_controller.rb](https://github.com/unixmonkey/wicked_pdf_issues/blob/master/app/controllers/pages_controller.rb).

Even then, you may need to be mindful of what assets are on that page (images, js, etc, could be loaded from a local URL, which also could cause the deadlock issue.

Please don't take any of the above as a negative. This is a complicated thing that can trip up anyone. There's a reason this project has so many open issues, but I'm still convinced it's the best free option we currently have for doing this. If you get stuck again or there's anything I can do to help, please let me know. If necessary I can possibly arrange a screenshare to help out.

You can do it. 😃

**Comment by henron1** [comment]
Thanks! I think the backticks were the kicker! I was using them since with template literals earlier and forgot to change it to quotes when I was hardcoding in the params. Thank you again.

**Comment by unixmonkey** [comment]
Closing this since it looks like you got it figured out. Please bump if you continue having issues.
