### ISSUE TITLE
Unable to generate pdf on RHEL6.8

### ISSUE THREAD

**Issue by mantri-govind** [mileszs/wicked_pdf#887]
## Issue description
I'm using `wicked-pdf` and its `binary` component on RHEL environment. However when I'm trying to generate pdf it is looking for `/etc/centos-release` file which doesn't exists in RHEL. Just to check exact issue I created this file and re-ran the code and got following error :

```
Invalid platform, must be running on Ubuntu 14.04/16.04/18.04 CentOS 6/7, Debian 8/9/10, or intel-based macOS (missing binary: /<app-path>/bundle/ruby/2.3.0/gems/wkhtmltopdf-binary-0.12.5.1/bin/wkhtmltopdf__amd64). (RuntimeError)
```
## Expected or desired behavior

It should have generated the pdf.

## System specifications

wicked_pdf (1.4.0)

wkhtmltopdf version (output of `wkhtmltopdf --version`):
NA
whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar):

RHEL 6.8

**Comment by unixmonkey** [comment]
This is not a problem with `wicked_pdf`, but with https://github.com/zakird/wkhtmltopdf_binary_gem, or maybe https://github.com/wkhtmltopdf/wkhtmltopdf, which seems to not have a current release for RHEL listed on [it's releases page](https://wkhtmltopdf.org/downloads.html).

That said, you should be able to install an older version (which will probably work just fine) with this:
```ruby
gem 'wkhtmltopdf-binary', '= 0.12.4'
```
or [these instructions](https://gist.github.com/ajaxray/e17c1ecd9ae9bb7310a2091e3db79616).

This is possible because versions below 0.12.5 had a generic linux binary, but due to issues with linking OpenSSL, there are now several distribution-specific binaries that you need to choose from, or build yourself.

**Comment by mantri-govind** [comment]
@unixmonkey Thanks I'll try and update if it works !
