### ISSUE TITLE
html_safe doesn't work

### ISSUE THREAD

**Issue by CamiMeneses** [mileszs/wicked_pdf#897]
document_text contains html code like:
`document_text = "<h1>hello</h1>"`
```
  doc = document_text

    doc_pdf = WickedPdf.new.pdf_from_string(
      ActionController::Base.new().render_to_string(
        :template =>  "clientdetails/document_pdf2.erb",
        :locals => {
          :@document_text => doc,
          :@signature => client_signature,
        },
        :layout => false,
      ),......
```
In my view
```
<%= @document_text.html_safe %>
<%== @document_text %>
<%= raw @document_text %>
<%= sanitize @document_text %>
<%= simple_format @document_text %>
```
i've tried many ways to not see the tags  when i build my pdf but it's impossible. Also, i've tried from the other file like  `doc = document_text.html_safe` and others

**Comment by unixmonkey** [comment]
I tried to reproduce this issue, but was not able to. It seems to work perfectly for me.
wicked_pdf (2.0.2)
wkhtmltopdf 0.12.5 (with patched qt)

Here's the exact code I used. I made some small adjustments to also add an escaped h1 at the top:
__app/controllers/issues_controller.rb__
```ruby
  def issue_897
    @document_text = "<h1>hello</h1>"

    respond_to do |format|
      format.html
      format.pdf {
        # render pdf: 'mypdf' # this works the same as the below code
        doc = @document_text

        doc_pdf = WickedPdf.new.pdf_from_string(
          html = ActionController::Base.new().render_to_string(
            :template =>  "issues/issue_897.erb",
            :locals => {
              :@document_text => doc,
            },
            :layout => false,
          )
        )
        send_data doc_pdf, type: 'application/pdf', disposition: 'inline'
      }
    end
  end
```
__app/views/issues/issue_897.erb__
```erb
<%= @document_text %>
<%= @document_text.html_safe %>
<%== @document_text %>
<%= raw @document_text %>
<%= sanitize @document_text %>
<%= simple_format @document_text %>
```

And this is a screenshot of the result PDF:
![Screen Shot 2020-03-28 at 10 59 15 AM](https://user-images.githubusercontent.com/8360/77826182-3eff6200-70e4-11ea-96d9-b5c724dcdacb.png)

Which looks the same as the HTML view.

What version of `wkhtmltopdf` and `wicked_pdf` are you using?

**Comment by CamiMeneses** [comment]
I'm calling a helper to generate this from a controller
```
  def self.generate_pdf
    doc_pdf = WickedPdf.new.pdf_from_string(
      ActionController::Base.new().render_to_string(
        :template =>  "clientdetails/document_pdf2.erb",
        :locals => {
          :@document_text => @document_text,
          :@signature => @client_signature,
          :@client_name => build_name
        },
        :layout => false,
      ),
      :pdf => "legal document",
      :layout => false,
      :page_size => 'Letter',
      :lowquality => false,
      :handlers => [:erb],
      :formats => [:html],
      :orientation => 'Portrait',
      :disposition => 'attachment',
      :show_as_html => 'true',
      :disable_external_links => false,
      :encoding => 'utf8',
      :margin => {
        :top            => 30,
        :bottom         => 20,
        :left           => 20,
        :right          => 20}
    )

    pdf_path = "#{@directory}/#{@filename}.pdf"
    File.open( pdf_path, "wb") do |file|
      file << doc_pdf
    end

    return pdf_path
  end
```
I make the file and then I save it in a local file...... because I upload the file later to aws s3
I made your exercise but it works like if I want to show the pdf in a view. I don't know I'm confused.

I'm using wicked_pdf (2.0.2) and wkhtmltopdf-binary (0.12.5.4). The readme says wkhtmltopdf-binary

**Comment by unixmonkey** [comment]
Can you post a screenshot of what you do see?

I just put all your code into a test project, tweaked the `pdf_path` for my system, commented out the `signature`, and `client_name`, and made `generate_pdf` an instance method helper (instead of a class method) and it's still working for me.

The reason I made it into an instance method, is because without it, there's no such method `.html_safe` available to a controller class, just an instance.

Here's what I have that is a straight-up copy and paste of what you posted (but with a few lines commented out that reference code I don't have) that is also working for me:

```ruby
  def issue_897
    @document_text = "<h1>hello</h1>"

    respond_to do |format|
      format.html
      format.pdf {
        doc_pdf = generate_pdf
        send_data doc_pdf.read, type: 'application/pdf', disposition: 'inline'
      }
    end
  end

  def generate_pdf
    doc_pdf = WickedPdf.new.pdf_from_string(
      ActionController::Base.new().render_to_string(
        :template =>  "issues/issue_897.erb",
        :locals => {
          :@document_text => @document_text,
          # :@signature => @client_signature,
          # :@client_name => build_name
        },
        :layout => false,
      ),
      :pdf => "legal document",
      :layout => false,
      :page_size => 'Letter',
      :lowquality => false,
      :handlers => [:erb],
      :formats => [:html],
      :orientation => 'Portrait',
      :disposition => 'attachment',
      :show_as_html => 'true',
      :disable_external_links => false,
      :encoding => 'utf8',
      :margin => {
        :top            => 30,
        :bottom         => 20,
        :left           => 20,
        :right          => 20}
    )

    # pdf_path = "#{@directory}/#{@filename}.pdf"
    pdf_path = Rails.root.join("tmp/testpdf_#{Time.now.to_i}.pdf")
    File.open( pdf_path, "wb") do |file|
      file << doc_pdf
    end

    return pdf_path
  end
```

I hope this helps some. Please post what you see. Is it escaped HTML, is it the PDF source as text?

**Comment by unixmonkey** [comment]
By the way, what operating system are you running on? Do you know what version of the `wkhtmltopdf` binary you are running.
You should be able to tell by running `bundle show wkhtmltopdf-binary`, then opening that directory, looking inside the `bin`, subdirectory, and seeing which file does not have the `.gz` extension (because your system uncompressed it).

I say this because even though the `wkhtmltopdf-binary` gem installs the binary for your system, sometimes to work fully, there should be other dependent libraries installed, like 'libjpeg', etc..

I don't think this is your problem, but it's possible. Without that, I would expect no PDFs work at all.

**Comment by CamiMeneses** [comment]
I think respond_to is to hit that method and show the pdf but i just want to save it. I cannot show it.
This is what i do before the generate_pdf method
![image](https://user-images.githubusercontent.com/47391280/77834680-5c4c2480-7114-11ea-9ae8-519afce1f793.png)
![image](https://user-images.githubusercontent.com/47391280/77834694-75ed6c00-7114-11ea-9e2d-1515a45fe120.png)
and about the gem this is what i get opening that file 
![image](https://user-images.githubusercontent.com/47391280/77834745-e09ea780-7114-11ea-8ef6-573cd5afd80b.png)
and i'm working on Linux Mint

**Comment by unixmonkey** [comment]
The way that I'm using `respond_to` above is just so I can see the PDF. I'm generating it as a file, then displaying it with `send_data`.

I was asking for a screenshot of the PDF you are generating, but isn't working for you, not the code, but that is helpful.

Because Mint is a fork of Ubuntu, I can see that you are using the Ubuntu 18.04 64-bit binary.

Do other PDFs work fine, and we are trying to make this work for a new case (`html_safe` markup inside the pdf), or is this infrastructure all recently written from scratch to handle this (like the `PdfHelper` module and the `generate_pdf` method)?

**Comment by CamiMeneses** [comment]
This is what I get.
![Captura de pantalla de 2020-03-30 17-12-33](https://user-images.githubusercontent.com/47391280/77967148-250f7c00-72aa-11ea-9f80-a6835aca0e3d.png)
![Captura de pantalla de 2020-03-30 17-16-28](https://user-images.githubusercontent.com/47391280/77967177-38224c00-72aa-11ea-832c-37d871ffdbe4.png)

**Comment by CamiMeneses** [comment]
I've realized the problem. Thank u so much

**Comment by unixmonkey** [comment]
Glad to help! Would you mind please posting what the issue turned out to be?

I think it could help others, or at least me, who frequently helps others here and on the `wkhtmltopdf-binary` project.

**Comment by unixmonkey** [comment]
@CamiMeneses Could you please post a summary of what solved the issue?
