### ISSUE TITLE
Failing Tests (WickedPdfHelperAssets)

### ISSUE THREAD

**Issue by fakefarm** [mileszs/wicked_pdf#902]
Hello, 
Thank you for all your hard work on this gem. It appears to still be the best solution after all these years. Kudos to you! During my installation process I was having some issues with connecting the styles, which I solved. However, during my process I forked the repo and ran the tests, to discover the following failures. Are these of interest to anyone? (If I get some time I will throw my hat in the ring)

```
# Running:

..F

Failure:
WickedPdfHelperAssetsTest#test_wicked_pdf_stylesheet_link_tag_should_inline_the_stylesheets_passed_in [/Users/volt/VOLT/Forks/wicked_pdf/test/functional/wicked_pdf_helper_assets_test.rb:14]:
--- expected
+++ actual
@@ -1,3 +1,2 @@
 "<style type='text/css'>/* Wicked styles */
-
 </style>"



rails test /Users/volt/VOLT/Forks/wicked_pdf/test/functional/wicked_pdf_helper_assets_test.rb:12

......F

Failure:
WickedPdfHelperAssetsTest#test_wicked_pdf_javascript_include_tag_should_inline_the_javascripts_passed_in [/Users/volt/VOLT/Forks/wicked_pdf/test/functional/wicked_pdf_helper_assets_test.rb:26]:
--- expected
+++ actual
@@ -1,3 +1,2 @@
-"<script type='text/javascript'>// Wicked js
-;
+"<script type='text/javascript'>// Wicked js;
 </script>"


rails test /Users/volt/VOLT/Forks/wicked_pdf/test/functional/wicked_pdf_helper_assets_test.rb:24

....................................

Finished in 5.141231s, 8.9473 runs/s, 28.2034 assertions/s.
```

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):
` wicked_pdf (2.0.2)`

wkhtmltopdf version (output of `wkhtmltopdf --version`):
`wkhtmltopdf 0.12.5 (with patched qt)`

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used: `wkhtmltopdf-binary (0.12.5.4)`

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar):

`mac`

**Comment by unixmonkey** [comment]
Thank you for noticing, however those tests will pass if ran with the right environment around them.
The https://github.com/mileszs/wicked_pdf/blob/master/.travis.yml file sets up the necessary versions of ruby, rails, sprockets, bundler, etc.

You can see the latest builds here: http://travis-ci.org/mileszs/wicked_pdf

Some versions of sprockets adds a newline, while others do not, and I don't think I'd consider that a failure, since it shouldn't affect how it works. I would consider a small fix so that the test no longer cares about the newline being added before the closing tags, though.
