### ISSUE TITLE
Rendering Japanese Characters in my PDF

### ISSUE THREAD

**Issue by Prabu2017** [mileszs/wicked_pdf#937]
I would like to import some japanese characters in the PDF. while coverting from HTML to PDF these japanese characters are getting converted to square symbol. This issue does not occurs in my local but it occurs in heroku server.

I would like to import some japanese characters in the PDF

Ubuntu

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):

    wicked_pdf (2.1.0)
  wicked_pdf

Heroku cedar

**Comment by unixmonkey** [comment]
It is likely because the server doesn't have those fonts installed, even though you already have them installed locally.

See this issue for a similar issue/solution description:

https://github.com/mileszs/wicked_pdf/issues/675
https://github.com/mileszs/wicked_pdf/issues/496

From a quick search, it seems that `apt-get install fonts-takao` should help you here.

**Comment by thomasnaude** [comment]
Hi @Prabu2017, we had the same issue on Heroku and [this seems to fix it](https://www.mschweighauser.com/custom-fonts-in-heroku-apps/)

**Comment by unixmonkey** [comment]
@thomasnaude Thanks for the pointer to that article. It's super short, so here's the gist of the fix it describes:

> For Japanese you can download the fonts from the same source as the official Ubuntu package: https://launchpad.net/takao-fonts.
> Then you create a folder called `.fonts` (including the dot) in your app root directory and copy all necessary fonts inside.
> Commit and push your app to Heroku. That's it!
