### ISSUE TITLE
Cloundinary image not rendered

### ISSUE THREAD

**Issue by Narf-stack** [mileszs/wicked_pdf#946]
## Issue description
Using wicked_pdf, I am rendering the show view of an Invoice model. Overall, the outcome is perfect exept for a cloudinary image that is not rendered. It actually works fine in development, but when the code is pushed it in production, the image disappear of the pdf.

I went through similar open issues, but I was not able to find any concrete answer. Also, as I used the debuging option I was able to retrieve the before mentioned image on the debug page. Looks like this issue only occur on the pdf.

## Expected or desired behavior

The cloudinary image should be present on the pdf in production. Like it does in development. 

## System specifications

Cloundinary:

`gem 'cloudinary', '~> 1.12.0'`

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):
 
```
wicked_pdf (2.1.0)
  wicked_pdf (~> 2.1)
```

wkhtmltopdf version (output of `wkhtmltopdf --version`):
`wkhtmltopdf 0.12.4 (with patched qt)`

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar):
```
Mac OS & Rails 5
 App deployed on Heroku with a domain name on OVH
```

**Comment by unixmonkey** [comment]
This is not enough information to determine the issue. It's very likely that the source being provided to `wkhtmltopdf` is either incomplete, or has a cross-protocol issue. It is also possible, but somewhat unlikely, that there are request requirements for the image server. It could also be that this image is being served by your same server, and is not in the asset manifest, or is incorrectly assumed to be in the rails `public` dir for some reason.

Please share how you are rendering the image in your Ruby source.

Is it like this: `<%= wicked_pdf_image_tag('path/to/file.jpg') %>` or `<img src="https://example.com/file.jpg'>` is it served by your rails server, or a 3rd-party cdn?

Please use the `show_as_html: true` flag, then right-click, view page source in your browser, and inspect the `<img>` tag.

Is it using a `file://` reference, is it a protocol-relative path like `//domain.com`, is it a relative reference like `/path/to/file.jpg`, or does it include base64 data?

Can you share the public URL for the image? Does it work for other images, just not this one?

**Comment by Narf-stack** [comment]
All my images are being handled by cloundinary, so I tend to render them like this :
`<%= cl_image_tag user.photo.key, height: 80, width: 80, crop: :fill,:style => "border-radius: 50%" %>`.

That being said I also tried to process them through wicked like this: 
`<%= wicked_pdf_image_tag user.photo.key, height: 80, width: 80, crop: :fill,:style => "border-radius: 50%" %>`

But nothing changed! 

Here is my `<img>` tag once I used `show_as_html: true`

`<img height="80" width="80" style="border-radius: 50%" src="http://res.cloudinary.com/www-hellomybusiness-fr/image/upload/c_fill,h_80,w_80/rxtRmLn1egsh44ejv9XZkpRE" />` 

The result is the same for all my images. They are correctly displayed in `development`, but disappear from the PDF once in `production`.
here is the public URL to my image:
`http://res.cloudinary.com/www-hellomybusiness-fr/image/upload/c_fill,h_80,w_80/rxtRmLn1egsh44ejv9XZkpRE`

**Comment by unixmonkey** [comment]
Ok, so I just tried this out myself, and everything seems fine to me. The photo renders with the provided image tag both through raw `wkhtmltopdf`, and through WickedPdf.

Because you are only seeing this issue in production, I suspect your production server is possibly misconfigured somehow.
It could be the version of `wkhtmltopdf` installed isn't compiled with everything needed to display images, or there are additional packages that need installed on your host like `libjpeg`, or the user that it executes as won't allow it to run, or it runs through a binary stub that uses a different ruby version, or the cloudinary config is different there. I'm not sure.

Here's some things you could check to see if there's anything funny going on:
```shell
# check wkhtmltopdf binary location
which wkhtmltopdf
# check wkhtmltopdf version on server
wkhtmltopdf --version
# check wkhtmltopdf can render a pdf with your image
 echo '<img height="80" width="80" style="border-radius: 50%" src="http://res.cloudinary.com/www-hellomybusiness-fr/image/upload/c_fill,h_80,w_80/rxtRmLn1egsh44ejv9XZkpRE" />' > test.html
wkhtmltopdf test.html test.pdf
```

I hadn't heard of OVH before, but a little googling tells me it's likely a problem with their hosting:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2691

That thread mentions that you may need to use a fat/static binary that includes supporting libraries like libjpeg, which means you may have to use an older version of `wkhtmltopdf`, although 0.12.4 is one of those, so hopefully that works for you.

You may have better luck if you use the `https://github.com/zakird/wkhtmltopdf_binary_gem/`, or unpack the necessary gem binary into your project something like this:
```shell
cd "$(bundle show wkhtmltopdf-binary)/bin"
cp wkhtmltopdf_linux_amd64 <Rails_dir>/bin
```
And setup your initializer to use that only in production something like this:
```ruby
config = {}
config[:exe_path] = Rails.root.join('bin', 'wkhtmltopdf_linux_amd64').to_s if Rails.env.production?
WickedPdf.config = config
```

Please let me know how it goes!

**Comment by Narf-stack** [comment]
So, I found a workaround way to my issue. Once created, the newly generated PDF will be directly uploaded to Cloundinary. This way I am able to keep my image rendered.
Thank you for you help.
