### ISSUE TITLE
Wicked PDF: RuntimeError: Failed to execute

### ISSUE THREAD

**Issue by MittalPatel-BTC** [mileszs/wicked_pdf#953]
## Issue description
I am facing this issue in my live server and below is the detailed error logs

RuntimeError: Failed to execute:
["/usr/bin/wkhtmltopdf", "-q", "--encoding", "utf8", "--page-size", "A4", "--margin-bottom", "40", "--footer-html", "file:////tmp/wicked_footer_pdf20201111-17075-q10v06.html", "file:////tmp/wicked_pdf20201111-17075-1rlm0b5.html", "/tmp/wicked_pdf_generated_file20201111-17075-319tez.pdf"]
Error: PDF could not be generated!
 Command Error: The switch --footer-html, is not support using unpatched qt, and will be ignored.qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.

## Configuration of Wicked PDF on my system

```
WickedPdf.config[:page_size] = 'A4'
WickedPdf.config[:formats] = :html
WickedPdf.config[:encoding] = 'utf8'
```

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):
```
  remote: https://github.com/mileszs/wicked_pdf.git
    wicked_pdf (2.1.0)
      wicked_pdf
  wicked_pdf!
```
wkhtmltopdf version (output of `wkhtmltopdf --version`):
```
wkhtmltopdf 0.12.3 (with patched qt)
```
whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar):
```
Ubuntu VERSION=18.04 
```
Ruby and Rails version
```
ruby 2.6.3
Rails 5.2.3
```

**Comment by MittalPatel-BTC** [comment]
@unixmonkey: Any update on this?

**Comment by unixmonkey** [comment]
> The switch --footer-html, is not support using unpatched qt, and will be ignored.qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.

This tells me these 2 things are happening, and neither of them have to do with wicked_pdf, but I'll try to help anyway:

> is not support using unpatched qt, and will be ignored.

This means the version of `wkhtmltopdf` you are using isn't compiled with QT support (also you are using a pretty oldish version). Try installing [the wkhtmltopdf gem](https://github.com/zakird/wkhtmltopdf_binary_gem/), or one of the official [wkhtmltopdf downloads](https://wkhtmltopdf.org/downloads.html) which are compiled with QT support.

> Could not connect to any X display.

This means it tried to connect the virtual web browser `wkhtmltopdf` uses to a "screen", but couldn't.

Again, I think this will be fixed with one of the above builds, but you may need to install `xvfb` and set your `wkthmltopdf` to run with `xvfb-run`. Search those terms in the README and issues of this project for more detail.

Good luck!

**Comment by MittalPatel-BTC** [comment]
@unixmonkey: Thanks for your response.

I have tried the below fix and it works for me
> https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2037#issuecomment-344423993
